### ISSUE TITLE
view vertically centers incorrectly  while zooming if lineage interface opened in a lower pane

### ISSUE THREAD

**Issue by cheezopath** [ycnmhd/obsidian-lineage#60] opened 2024-07-04 08:43 UTC
### Are you using the latest version of the plugin?

- [X] I have verified that I am using the latest version

### Have you checked for similar issues?

- [X] I have verified that there are no similar issues

### What happened?

if I have a vertical split in my workspace and open lineage view on a lower or non-top aligned pane, the vertical align of the active card is offset too high

### What did you expect to happen?

active card element to be centred in the pane. likely an absolute value/offset issue

### Obsidian version

1.6.5

### OS

Windows

**Comment by ycnmhd** [comment] 2024-07-04 09:48
Can you provide a screenshot of the issue?

**Comment by cheezopath** [comment] 2024-07-04 09:57
![image](https://github.com/ycnmhd/obsidian-lineage/assets/8531235/2db2f8ac-f93b-4aff-992f-4f4d2b7a235f)

in the screenshot I scrolled up a little in the lower pane to show that the card is present but higher up. at first it's all the way offscreen

**Comment by ycnmhd** [comment] 2024-07-04 11:49
Does the issue persist when the zoom is set to 1 (no zoom)?

**Comment by cheezopath** [comment] 2024-07-04 12:00
yep!

**Comment by cheezopath** [comment] 2024-07-04 12:01
whoops sorry misclicked close....

**Comment by ycnmhd** [comment] 2024-07-04 12:17
I can't reproduce this issue (unless zoom is not set to 1)
![2024-07-04_13-13-54](https://github.com/ycnmhd/obsidian-lineage/assets/33285087/8d7f457f-e427-4a9a-812b-653422b6dd0d)

**Comment by cheezopath** [comment] 2024-07-04 12:26
tried in a new vault. I think something to do with the order of opening/window splitting has an impact on the behaviour but can't pin it down exactly yet

https://github.com/ycnmhd/obsidian-lineage/assets/8531235/159eb08b-77c3-46b4-a132-d41b023b1213

**Comment by cheezopath** [comment] 2024-07-04 12:33
sorry just spotted that this wasnt at zoom zero. when i retry after selecting reset zoom in the interface it started working again. weird as I am almost certain i didnt change zoom level when making the new vault. maybe I had selected fit? Things do break at non default zoom as you say

**Comment by ycnmhd** [comment] 2024-12-14 21:49
Fixed in 0.7.0

**Closed as completed by ycnmhd** 2024-12-14 21:49 UTC
Labels: bug
